apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_USER: tms
  POSTGRES_PASSWORD: hui123
  POSTGRES_DB: tms
  POSTGRES_HOST: db
  DATABASE_URL: postgres://tms:hui123@db:5432/tms
